services:
  app:
    build: .
    ports:
      - 5000:5000
      - 5001:5001
    links:
      - db
    depends_on:
      - db
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=todoappdb-dev;Username=postgres;Password=password
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: todoappdb-dev
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data: