CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Users" (
    "Username" text NOT NULL,
    "PasswordHash" text NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Username")
);

CREATE TABLE "UserTasks" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Username" text NULL,
    CONSTRAINT "PK_UserTasks" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_UserTasks_Users_Username" FOREIGN KEY ("Username") REFERENCES "Users" ("Username")
);

CREATE TABLE "Subtasks" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "Completed" boolean NOT NULL,
    "OwnerTaskID" integer NOT NULL,
    CONSTRAINT "PK_Subtasks" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Subtasks_UserTasks_OwnerTaskID" FOREIGN KEY ("OwnerTaskID") REFERENCES "UserTasks" ("ID")
);

CREATE INDEX "IX_Subtasks_OwnerTaskID" ON "Subtasks" ("OwnerTaskID");

CREATE INDEX "IX_UserTasks_Username" ON "UserTasks" ("Username");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231213171048_Initial', '7.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "Subtasks" DROP CONSTRAINT "FK_Subtasks_UserTasks_OwnerTaskID";

ALTER TABLE "Subtasks" ADD CONSTRAINT "FK_Subtasks_UserTasks_OwnerTaskID" FOREIGN KEY ("OwnerTaskID") REFERENCES "UserTasks" ("ID") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231213171739_FixCascade', '7.0.0');

COMMIT;

